### ISSUE TITLE
Symbol() of null on v-if true after false

### ISSUE THREAD

**Issue by ChadMcCaulley** [privatenumber/vue-frag#16]
Setting v-if to false removes element, but changing back to true returns:
[Vue warn]: Error in directive frag inserted hook: "TypeError: Cannot read property 'Symbol()' of null"

`TypeError: Cannot read property 'Symbol()' of null
    at eval (frag.esm.js?76e6:1)
    at inserted (frag.esm.js?76e6:1)
    at callHook$1 (vue.runtime.esm.js?2b0e:6680)
    at callInsert (vue.runtime.esm.js?2b0e:6619)
    at wrappedHook (vue.runtime.esm.js?2b0e:2235)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
    at Object.invoker [as insert] (vue.runtime.esm.js?2b0e:2175)
    at invokeInsertHook (vue.runtime.esm.js?2b0e:6346)
    at VueComponent.patch [as __patch__] (vue.runtime.esm.js?2b0e:6565)
    at VueComponent.Vue._update (vue.runtime.esm.js?2b0e:3948)`

**Comment by privatenumber** [comment]
Seems to work fine: https://codepen.io/privatenumber/pen/dypqEXb

Can you provide a reproduction?

**Comment by privatenumber** [comment]
Closing since stale

**Comment by 3nuc** [comment]
@privatenumber I managed to reproduce this. Can you please reopen this issue if the repro is ok?

https://codesandbox.io/s/github/3nuc/vue-frag-issue-16?file=/src/App.vue

Conditions for this to happen:
* (MyInput.vue) a component needs to have a root node that has a v-if on itself. That root node also needs to have v-frag
* next to that component, create div with v-if
* toggle visibility of both elements

Yeah you really need to do some ancient shamanic ritual to trigger this

**Comment by privatenumber** [comment]
Thanks @3nuc 

I trimmed it further to this: https://codesandbox.io/s/admiring-minsky-zek6q?file=/src/MyInput.vue

I also tried reproducing the exact code in JSFiddle for something more bare but couldn't reproduce.
https://jsfiddle.net/hirokiosame/zyrd8q7w/

I'm currently curious if it's related to vue-loader/Vue CLI. Will experiment further.

**Comment by privatenumber** [comment]
Fix released in v1.2.1

**Comment by 3nuc** [comment]
@privatenumber I see that my previous repro doesn't trigger the error anymore. Thanks!

I updated to 1.2.1 in my work app and unfortunately the error still persists there. Looks like my repro case was only one of N possible cases
I've managed to reproduce the same error under 1.2.1 - I just added 2 MyInputs with :visible next to eachother  - https://codesandbox.io/s/github/3nuc/vue-frag-issue-16

**Comment by privatenumber** [comment]
Good catch!

**Comment by privatenumber** [comment]
This case is still bugging: https://jsfiddle.net/hirokiosame/tfjp85g1/

**Comment by 3nuc** [comment]
Thanks! Managed to find this on 1.2.3 too: 
https://jsfiddle.net/astg047y/4/

You're fixing the repros so well and then I come out with some crazy/stupid edge case like adding the second toggler above 😅 Please let me know if they're getting too ridiculous

**Comment by privatenumber** [comment]
@3nuc

**Comment by privatenumber** [comment]
Thanks for that test @3nuc 

Surfaced a lot of edge-cases and bugs that helped me come to a more holistic approach.

I hope it's solid now: https://jsfiddle.net/hirokiosame/vfxc594p/

**Comment by 3nuc** [comment]
>I hope it's solid now

Yep, it is :tada: Tested on my app where the error happened on 1.2.1-1.2.3 but 1.2.4 fixes it :)

Thanks so much!

**Comment by 3nuc** [comment]
There's still one edge case out there. Experiencing it in my project right now but haven't been able to reproduce in jsfiddle yet.

```
TypeError: can't access property Symbol(), parent is null
  patchParentMethods frag.esm.js:124
```

**Comment by privatenumber** [comment]
@3nuc please let me know when you are able to reproduce it 🙏

**Comment by privatenumber** [comment]
@sethidden 

I released a refactor with exhaustive tests to make sure the DOM APIs return the exact expected values.

Do you mind seeing if that works better for you?
